"""Create a reproducible scenario bank for fair multi-policy evaluation."""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from config import PROCESSED_DIR, RANDOM_SEED, SCENARIO_COUNT, ensure_directories


def build_scenario_bank(count: int, seed: int) -> pd.DataFrame:
    rng = np.random.default_rng(int(seed))
    # Seeds are recorded for auditability; event-level randomness is generated by hashing
    # scenario_id, seed, event index and draw name inside ScenarioRandomness.
    return pd.DataFrame(
        {
            "scenario_id": np.arange(int(count), dtype=int),
            "base_seed": rng.integers(1, 2**31 - 1, size=int(count), dtype=np.int64),
        }
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Build common-random-number scenario bank")
    parser.add_argument("--count", type=int, default=SCENARIO_COUNT)
    parser.add_argument("--seed", type=int, default=RANDOM_SEED)
    args = parser.parse_args()
    ensure_directories()
    df = build_scenario_bank(args.count, args.seed)
    out = PROCESSED_DIR / "scenario_bank.csv"
    df.to_csv(out, index=False)
    print(f"Saved {len(df)} scenarios to {out}")


if __name__ == "__main__":
    main()
